"""Add grade table

Revision ID: 6385e2fc23c6
Revises: 75589bb37119
Create Date: 2025-02-24 17:25:41.773913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6385e2fc23c6'
down_revision = '75589bb37119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_instructor', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_student', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_instructor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_student', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_student')
        batch_op.drop_column('is_instructor')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_student')

    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.drop_column('is_instructor')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    op.drop_table('grade')
    # ### end Alembic commands ###
