"""Updated migration with student-course many-to-many and instructor-course one-to-one

Revision ID: 75589bb37119
Revises: 
Create Date: 2025-02-20 11:50:49.811520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75589bb37119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('course_instructor_id_fkey', type_='foreignkey')
        batch_op.drop_column('instructor_id')

    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['course_id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('course_instructor_id_fkey', 'instructor', ['instructor_id'], ['id'])

    op.drop_table('student_course')
    # ### end Alembic commands ###
