"""Remove course_id from Instructor and adjust relationships

Revision ID: 94a4861e6e5a
Revises: 2ad3de8f3d67
Create Date: 2025-03-04 08:07:13.027524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a4861e6e5a'
down_revision = '2ad3de8f3d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instructor', ['instructor_id'], ['id'])

    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.drop_constraint('instructor_course_id_key', type_='unique')
        batch_op.drop_constraint('instructor_course_id_fkey', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('instructor_course_id_fkey', 'course', ['course_id'], ['id'])
        batch_op.create_unique_constraint('instructor_course_id_key', ['course_id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instructor_id')

    # ### end Alembic commands ###
