"""Add image and modules to Course, update Grade grade type

Revision ID: e07620f746de
Revises: 94a4861e6e5a
Create Date: 2025-03-04 22:25:27.337549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07620f746de'
down_revision = '94a4861e6e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('modules', sa.JSON(), nullable=True))

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.String(length=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('modules')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
